### PR TITLE
Docs imported from studio/master

### PR DESCRIPTION
**Pull request by benjaoming**

### CODE REVIEW

**Comment by benjaoming** [comment]
CC: @radinamatic - docs imported from studio.

Will import the develop branch, too.

**Comment by radinamatic** [comment]
Yey, first PR on this ganz neu repo!!! ❤️ 👍 🌟 

Thank you so much @benjaoming for setting this up!!! 🙇‍♀️

**Comment by benjaoming** [comment]
It's so nice to get docs split out... I also wondered a bit about having these constant Read The Docs rebuilds for no reason... really bad for the environment to have hundreds if not thousands of build jobs for no reason.

**Comment by radinamatic** [comment]
And now they are officially 💥

**Pull request merged**
