### PR TITLE
fixing bullets and updating readme

### LINKED ISSUE #24: bulletted lists are not rendering correctly
This looks similar to behavior observed in Kolibri dev docs: https://github.com/learningequality/kolibri/issues/7958

see for example https://kolibri-studio.readthedocs.io/en/latest/add_content.html?#html5-applications

image

cc @radinamatic

### PR DESCRIPTION
**Pull request by indirectlylit**
* Tries to fix bulleted lists using strategy from https://github.com/learningequality/kolibri/pull/8002/files (fixes https://github.com/learningequality/studio-docs/issues/24)
* Pins other unpinned dependencies to current most recent versions
* Removes outdated badges and updates readme text slightly

### CODE REVIEW

**Comment by radinamatic** [comment]
Bulleted lists look fine when built locally with these dependency pins, but the problem on Kolibri docs presented itself only on RTD.

LEDev2104 (start)  Running  - Oracle VM VirtualBox_007

Let's merge and see! 🤞🏽

**Review by radinamatic — APPROVED** [review]
LGTM, thank you! 👍🏽

**Comment by radinamatic** [comment]
Looking green! 🎉 

Selection_010

**Comment by indirectlylit** [comment]
awesome, thanks for verifying.

there was a recent forum thread where someone linked to studio docs, and the broken formatting really bothered me :)

**Pull request merged**
